name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Build amp
        run: nix build .#amp --print-build-logs
      - name: Shell smoke test
        run: bash ./test/urn__entry__nix-shell-amp-help.sh
      - name: Run smoke test
        run: bash ./test/urn__entry__nix-run-amp-help.sh
